import { promises as fs } from "node:fs";
import path from "node:path";

const GALLERY_DIR = path.resolve(process.cwd(), "public", "assets", "gallery");
const OUTPUT_FILE = path.resolve(process.cwd(), "src", "data", "generated-gallery-photos.ts");

const IMAGE_EXTENSIONS = new Set([".png", ".jpg", ".jpeg", ".PNG", ".JPG", ".JPEG"]);
const VIDEO_EXTENSIONS = new Set([".mp4", ".webm", ".ogg", ".mov", ".MP4", ".WEBM", ".OGG", ".MOV"]);

async function walkDir(dir) {
	const entries = await fs.readdir(dir, { withFileTypes: true });
	const files = await Promise.all(
		entries.map(async (entry) => {
			const fullPath = path.join(dir, entry.name);
			if (entry.isDirectory()) {
				return walkDir(fullPath);
			}
			return fullPath;
		})
	);
	return files.flat();
}

function toPublicUrl(absoluteFilePath) {
	// Map absolute path under public/assets/gallery -> /assets/gallery/... (with forward slashes)
	const rel = path.relative(path.resolve(process.cwd(), "public"), absoluteFilePath);
	return "/" + rel.split(path.sep).join("/");
}

async function generate() {
	try {
		// Ensure output directory exists
		await fs.mkdir(path.dirname(OUTPUT_FILE), { recursive: true });

		// If gallery dir doesn't exist, write empty list
		let allFiles = [];
		try {
			allFiles = await walkDir(GALLERY_DIR);
		} catch {
			// keep empty
		}

		const imageFiles = allFiles.filter((f) => IMAGE_EXTENSIONS.has(path.extname(f)));
		const videoFiles = allFiles.filter((f) => VIDEO_EXTENSIONS.has(path.extname(f)));

		// Tập tên cơ sở của video để loại trừ ảnh trùng base name
		const videoBaseNames = new Set(videoFiles.map((vf) => path.basename(vf, path.extname(vf))));

		const items = imageFiles
			.sort((a, b) => a.localeCompare(b))
			// loại ảnh có cùng base name với bất kỳ video
			.filter((absPath) => !videoBaseNames.has(path.basename(absPath, path.extname(absPath))))
			.map((absPath, index) => {
				const url = toPublicUrl(absPath);
				const base = path.basename(absPath, path.extname(absPath));
				const id = `photo-${index + 1}-${base}`;
				return { id, src: url };
			});

		const fileContent = `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-gallery.mjs
export const generatedGalleryPhotos = ${JSON.stringify(items, null, 2)} as const;
`;

		await fs.writeFile(OUTPUT_FILE, fileContent, "utf8");
		console.log(`[gallery] Wrote ${items.length} photos to ${path.relative(process.cwd(), OUTPUT_FILE)}`);
	} catch (err) {
		console.error("[gallery] Failed to generate photos:", err);
		process.exitCode = 1;
	}
}

generate();
