// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-gallery.mjs
export const generatedGalleryPhotos = [
  {
    "id": "photo-1-a",
    "src": "/assets/gallery/a.png"
  },
  {
    "id": "photo-2-b",
    "src": "/assets/gallery/b.jpg"
  },
  {
    "id": "photo-3-c",
    "src": "/assets/gallery/c.png"
  },
  {
    "id": "photo-4-d",
    "src": "/assets/gallery/d.jpg"
  },
  {
    "id": "photo-5-e",
    "src": "/assets/gallery/e.png"
  },
  {
    "id": "photo-6-f",
    "src": "/assets/gallery/f.jpg"
  },
  {
    "id": "photo-7-g",
    "src": "/assets/gallery/g.png"
  }
] as const;
