// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-home.mjs
export const generatedHomeVideos: ReadonlyArray<{ id: string; src: string }> = [
  {
    "id": "home-video-1-quocca",
    "src": "/assets/home/quocca.mp4"
  }
];
